Repository jenkinsci/kubernetes-credentials-plugin, pull requests merged in 2024-08, with the labels that each got.

#50 [JENKINS-73525] add FIPS compliance checks to plugin when running in FIPS mode
  pom.xml
  src/main/java/org/jenkinsci/plugins/kubernetes/auth/KubernetesAuthConfig.java
  src/main/java/org/jenkinsci/plugins/kubernetes/credentials/HttpClientWithTLSOptionsFactory.java
  src/main/java/org/jenkinsci/plugins/kubernetes/credentials/OpenShiftBearerTokenCredentialImpl.java
  src/main/java/org/jenkinsci/plugins/kubernetes/credentials/Utils.java
  src/test/java/org/jenkinsci/plugins/kubernetes/auth/AbstractKubernetesAuthConfigFIPSTest.java
  src/test/java/org/jenkinsci/plugins/kubernetes/auth/KubernetesAuthConfigWithFIPSTest.java
  src/test/java/org/jenkinsci/plugins/kubernetes/auth/KubernetesAuthConfigWithoutFIPSTest.java
  src/test/java/org/jenkinsci/plugins/kubernetes/credentials/AbstractHttpClientWithTLSOptionsFactoryFIPSTest.java
  src/test/java/org/jenkinsci/plugins/kubernetes/credentials/AbstractOpenShiftBearerTokenCredentialFIPSTest.java
  src/test/java/org/jenkinsci/plugins/kubernetes/credentials/AbstractUtilsFIPSTest.java
  src/test/java/org/jenkinsci/plugins/kubernetes/credentials/HttpClientWithTLSOptionsFactoryWithFIPSTest.java
  src/test/java/org/jenkinsci/plugins/kubernetes/credentials/HttpClientWithTLSOptionsFactoryWithoutFIPSTest.java
  src/test/java/org/jenkinsci/plugins/kubernetes/credentials/OpenShiftBearerTokenCredentialWithFIPSTest.java
  src/test/java/org/jenkinsci/plugins/kubernetes/credentials/OpenShiftBearerTokenCredentialWithoutFIPSTest.java
  src/test/java/org/jenkinsci/plugins/kubernetes/credentials/UtilsWithFIPSTest.java
  src/test/java/org/jenkinsci/plugins/kubernetes/credentials/UtilsWithoutFIPSTest.java
  src/test/resources/org/jenkinsci/plugins/kubernetes/credentials/keystore.jks
Labels: enhancement

#55 [JENKINS-73610] Allow for null values in "ensureFIPS" methods
  src/main/java/org/jenkinsci/plugins/kubernetes/credentials/Utils.java
  src/test/java/org/jenkinsci/plugins/kubernetes/credentials/AbstractHttpClientWithTLSOptionsFactoryFIPSTest.java
  src/test/java/org/jenkinsci/plugins/kubernetes/credentials/AbstractOpenShiftBearerTokenCredentialFIPSTest.java
  src/test/java/org/jenkinsci/plugins/kubernetes/credentials/AbstractUtilsFIPSTest.java
  src/test/java/org/jenkinsci/plugins/kubernetes/credentials/HttpClientWithTLSOptionsFactoryWithFIPSTest.java
  src/test/java/org/jenkinsci/plugins/kubernetes/credentials/HttpClientWithTLSOptionsFactoryWithoutFIPSTest.java
  src/test/java/org/jenkinsci/plugins/kubernetes/credentials/UtilsWithFIPSTest.java
  src/test/java/org/jenkinsci/plugins/kubernetes/credentials/UtilsWithoutFIPSTest.java
Labels: bug

#54 [JENKINS-73139] Converting tests to `com.sun.net.httpserver`
  src/test/java/org/jenkinsci/plugins/kubernetes/credentials/AbstractOpenShiftBearerTokenCredentialFIPSTest.java
  src/test/java/org/jenkinsci/plugins/kubernetes/credentials/MockHttpServlet.java
  src/test/java/org/jenkinsci/plugins/kubernetes/credentials/OpenShiftBearerTokenCredentialMockServer.java
  src/test/java/org/jenkinsci/plugins/kubernetes/credentials/OpenShiftBearerTokenCredentialTest.java
Labels: developer, test
